changeskin_TD[0] = TextDrawCreate(368.6856, 331.7500, "LD_BEAT:right"); // ïóñòî
TextDrawTextSize(changeskin_TD[0], 37.0000, 41.0000);
TextDrawAlignment(changeskin_TD[0], TEXT_DRAW_ALIGN:1);
TextDrawColour(changeskin_TD[0], 65535);
TextDrawBackgroundColour(changeskin_TD[0], 255);
TextDrawFont(changeskin_TD[0], TEXT_DRAW_FONT:4);
TextDrawSetProportional(changeskin_TD[0], false);
TextDrawSetShadow(changeskin_TD[0], 0);
TextDrawSetSelectable(changeskin_TD[0], true);

changeskin_TD[1] = TextDrawCreate(239.0939, 332.1163, "LD_BEAT:left"); // ïóñòî
TextDrawTextSize(changeskin_TD[1], 35.0000, 42.0000);
TextDrawAlignment(changeskin_TD[1], TEXT_DRAW_ALIGN:1);
TextDrawColour(changeskin_TD[1], 65535);
TextDrawBackgroundColour(changeskin_TD[1], 255);
TextDrawFont(changeskin_TD[1], TEXT_DRAW_FONT:4);
TextDrawSetProportional(changeskin_TD[1], false);
TextDrawSetShadow(changeskin_TD[1], 0);
TextDrawSetSelectable(changeskin_TD[1], true);

changeskin_TD[2] = TextDrawCreate(321.8594, 364.9999, "BUY"); // ïóñòî
TextDrawLetterSize(changeskin_TD[2], 0.3379, 1.8507);
TextDrawTextSize(changeskin_TD[2], 20.0000, 63.0000);
TextDrawAlignment(changeskin_TD[2], TEXT_DRAW_ALIGN:2);
TextDrawColour(changeskin_TD[2], -10747649);
TextDrawUseBox(changeskin_TD[2], true);
TextDrawBoxColour(changeskin_TD[2], 130);
TextDrawSetOutline(changeskin_TD[2], 1);
TextDrawBackgroundColour(changeskin_TD[2], 255);
TextDrawFont(changeskin_TD[2], TEXT_DRAW_FONT:2);
TextDrawSetProportional(changeskin_TD[2], true);
TextDrawSetShadow(changeskin_TD[2], 0);
TextDrawSetSelectable(changeskin_TD[2], true);

changeskin_TD[3] = TextDrawCreate(321.8594, 391.8333, "EXIT"); // ïóñòî
TextDrawLetterSize(changeskin_TD[3], 0.3249, 1.9441);
TextDrawTextSize(changeskin_TD[3], 20.0000, 62.0000);
TextDrawAlignment(changeskin_TD[3], TEXT_DRAW_ALIGN:2);
TextDrawColour(changeskin_TD[3], -10747649);
TextDrawUseBox(changeskin_TD[3], true);
TextDrawBoxColour(changeskin_TD[3], 130);
TextDrawSetOutline(changeskin_TD[3], 1);
TextDrawBackgroundColour(changeskin_TD[3], 255);
TextDrawFont(changeskin_TD[3], TEXT_DRAW_FONT:2);
TextDrawSetProportional(changeskin_TD[3], true);
TextDrawSetShadow(changeskin_TD[3], 0);
TextDrawSetSelectable(changeskin_TD[3], true);

Logo[0] = TextDrawCreate(566.2403, 20.8330, "LIGHT");
TextDrawLetterSize(Logo[0], 0.3183, 1.0816);
TextDrawTextSize(Logo[0], 0.3999, 49.0000);
TextDrawAlignment(Logo[0], TEXT_DRAW_ALIGN:2);
TextDrawColour(Logo[0], -1);
TextDrawSetOutline(Logo[0], 1);
TextDrawBackgroundColour(Logo[0], 65347);
TextDrawFont(Logo[0], TEXT_DRAW_FONT:3);
TextDrawSetProportional(Logo[0], true);
TextDrawSetShadow(Logo[0], 0);

Logo[1] = TextDrawCreate(566.7905, 25.5166, "ISLAND");
TextDrawLetterSize(Logo[1], 0.4702, 1.5999);
TextDrawTextSize(Logo[1], 612.0000, -0.2099);
TextDrawAlignment(Logo[1], TEXT_DRAW_ALIGN:1);
TextDrawColour(Logo[1], 91881471);
TextDrawSetOutline(Logo[1], -512);
TextDrawBackgroundColour(Logo[1], 285212671);
TextDrawFont(Logo[1], TEXT_DRAW_FONT:3);
TextDrawSetProportional(Logo[1], true);
TextDrawSetShadow(Logo[1], 1);

/*Logo[2] = TextDrawCreate(591.1271, 40.9000, "RPG");
TextDrawLetterSize(Logo[2], 0.2702, 1.3999);
TextDrawAlignment(Logo[2], TEXT_DRAW_ALIGN:2);
TextDrawColour(Logo[2], -10682113);
TextDrawSetOutline(Logo[2], 1);
TextDrawBackgroundColour(Logo[2], 255);
TextDrawFont(Logo[2], TEXT_DRAW_FONT:3);
TextDrawSetProportional(Logo[2], true);
TextDrawSetShadow(Logo[2], 0);*/

textVelocimetro[0] = TextDrawCreate(458.000000, 378.000000, "i");
TextDrawBackgroundColour(textVelocimetro[0], 0);
TextDrawFont(textVelocimetro[0], TEXT_DRAW_FONT:2);
TextDrawLetterSize(textVelocimetro[0], 28.800073, 2.600000);
TextDrawColour(textVelocimetro[0], 80);
TextDrawSetOutline(textVelocimetro[0], 0);
TextDrawSetProportional(textVelocimetro[0], true);
TextDrawSetShadow(textVelocimetro[0], 1);
TextDrawSetSelectable(textVelocimetro[0], false);

textVelocimetro[1] = TextDrawCreate(458.000000, 392.000000, "i");
TextDrawBackgroundColour(textVelocimetro[1], 0);
TextDrawFont(textVelocimetro[1], TEXT_DRAW_FONT:2);
TextDrawLetterSize(textVelocimetro[1], 28.800073, 2.600000);
TextDrawColour(textVelocimetro[1], 80);
TextDrawSetOutline(textVelocimetro[1], 0);
TextDrawSetProportional(textVelocimetro[1], true);
TextDrawSetShadow(textVelocimetro[1], 1);
TextDrawSetSelectable(textVelocimetro[1], false);

textVelocimetro[2] = TextDrawCreate(458.000000, 406.000000, "i");
TextDrawBackgroundColour(textVelocimetro[2], 0);
TextDrawFont(textVelocimetro[2], TEXT_DRAW_FONT:2);
TextDrawLetterSize(textVelocimetro[2], 28.800073, 2.600000);
TextDrawColour(textVelocimetro[2], 80);
TextDrawSetOutline(textVelocimetro[2], 0);
TextDrawSetProportional(textVelocimetro[2], true);
TextDrawSetShadow(textVelocimetro[2], 1);
TextDrawSetSelectable(textVelocimetro[2], false);

textVelocimetro[3] = TextDrawCreate(458.000000, 420.000000, "i");
TextDrawBackgroundColour(textVelocimetro[3], 0);
TextDrawFont(textVelocimetro[3], TEXT_DRAW_FONT:2);
TextDrawLetterSize(textVelocimetro[3], 28.800073, 2.600000);
TextDrawColour(textVelocimetro[3], 80);
TextDrawSetOutline(textVelocimetro[3], 0);
TextDrawSetProportional(textVelocimetro[3], true);
TextDrawSetShadow(textVelocimetro[3], 1);
TextDrawSetSelectable(textVelocimetro[3], false);

textVelocimetro[4] = TextDrawCreate(531.000000, 387.000000, "Name~n~~n~Speed~n~~n~Fuel~n~~n~Health");
TextDrawAlignment(textVelocimetro[4], TEXT_DRAW_ALIGN:3);
TextDrawBackgroundColour(textVelocimetro[4], 0);
TextDrawFont(textVelocimetro[4], TEXT_DRAW_FONT:2);
TextDrawLetterSize(textVelocimetro[4], 0.210000, 0.799999);
TextDrawColour(textVelocimetro[4], -186);
TextDrawSetOutline(textVelocimetro[4], 0);
TextDrawSetProportional(textVelocimetro[4], true);
TextDrawSetShadow(textVelocimetro[4], 1);
TextDrawSetSelectable(textVelocimetro[4], false);

/*****************
* PLAYER INFO FRAME
*****************/
playerInfoFrameTD[0] = TextDrawCreate(218.0000, 330.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoFrameTD[0], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[0], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[0], 1094795775);
TextDrawSetShadow(playerInfoFrameTD[0], 0);
TextDrawSetOutline(playerInfoFrameTD[0], 0);
TextDrawBackgroundColour(playerInfoFrameTD[0], 255);
TextDrawSetProportional(playerInfoFrameTD[0], true);
TextDrawTextSize(playerInfoFrameTD[0], 200.0000, 70.0000);

playerInfoFrameTD[1] = TextDrawCreate(219.0000, 331.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoFrameTD[1], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[1], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[1], 589505535);
TextDrawSetShadow(playerInfoFrameTD[1], 0);
TextDrawSetOutline(playerInfoFrameTD[1], 0);
TextDrawBackgroundColour(playerInfoFrameTD[1], 255);
TextDrawSetProportional(playerInfoFrameTD[1], true);
TextDrawTextSize(playerInfoFrameTD[1], 30.0000, 68.0000);
TextDrawSetSelectable(playerInfoFrameTD[1], true);

playerInfoFrameTD[2] = TextDrawCreate(387.0000, 331.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoFrameTD[2], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[2], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[2], 589505535);
TextDrawSetShadow(playerInfoFrameTD[2], 0);
TextDrawSetOutline(playerInfoFrameTD[2], 0);
TextDrawBackgroundColour(playerInfoFrameTD[2], 255);
TextDrawSetProportional(playerInfoFrameTD[2], true);
TextDrawTextSize(playerInfoFrameTD[2], 30.0000, 68.0000);
TextDrawSetSelectable(playerInfoFrameTD[2], true);

playerInfoFrameTD[3] = TextDrawCreate(250.0000, 331.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoFrameTD[3], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[3], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[3], 589505535);
TextDrawSetShadow(playerInfoFrameTD[3], 0);
TextDrawSetOutline(playerInfoFrameTD[3], 0);
TextDrawBackgroundColour(playerInfoFrameTD[3], 255);
TextDrawSetProportional(playerInfoFrameTD[3], true);
TextDrawTextSize(playerInfoFrameTD[3], 136.0000, 68.0000);

playerInfoFrameTD[4] = TextDrawCreate(224.5000, 349.5000, "LD_BEAT:LEFT");
TextDrawFont(playerInfoFrameTD[4], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[4], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[4], 1684301055);
TextDrawSetShadow(playerInfoFrameTD[4], 0);
TextDrawSetOutline(playerInfoFrameTD[4], 0);
TextDrawBackgroundColour(playerInfoFrameTD[4], 255);
TextDrawSetProportional(playerInfoFrameTD[4], true);
TextDrawTextSize(playerInfoFrameTD[4], 20.0000, 28.0000);

playerInfoFrameTD[5] = TextDrawCreate(393.5000, 349.5000, "LD_BEAT:RIGHT");
TextDrawFont(playerInfoFrameTD[5], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoFrameTD[5], 0.5000, 1.0000);
TextDrawColour(playerInfoFrameTD[5], 1684301055);
TextDrawSetShadow(playerInfoFrameTD[5], 0);
TextDrawSetOutline(playerInfoFrameTD[5], 0);
TextDrawBackgroundColour(playerInfoFrameTD[5], 255);
TextDrawSetProportional(playerInfoFrameTD[5], true);
TextDrawTextSize(playerInfoFrameTD[5], 20.0000, 28.0000);

/*****************
* PLAYER INFO TEXTS
*****************/
playerInfoTD[0] = TextDrawCreate(302.0000, 333.5000, "NOW SPECTATING:");
TextDrawFont(playerInfoTD[0], TEXT_DRAW_FONT:1);
TextDrawLetterSize(playerInfoTD[0], 0.1399, 0.7999);
TextDrawColour(playerInfoTD[0], -1768515841);
TextDrawSetShadow(playerInfoTD[0], 0);
TextDrawSetOutline(playerInfoTD[0], 0);
TextDrawBackgroundColour(playerInfoTD[0], 255);
TextDrawSetProportional(playerInfoTD[0], true);
TextDrawTextSize(playerInfoTD[0], 640.0000, 0.0000);

playerInfoTD[1] = TextDrawCreate(252.0000, 333.5000, "PLAYER_MODEL");
TextDrawFont(playerInfoTD[1], TEXT_DRAW_FONT:5);
TextDrawLetterSize(playerInfoTD[1], 0.2099, 1.1000);
TextDrawColour(playerInfoTD[1], -1768515841);
TextDrawSetShadow(playerInfoTD[1], 0);
TextDrawSetOutline(playerInfoTD[1], 0);
TextDrawBackgroundColour(playerInfoTD[1], 1684301055);
TextDrawSetProportional(playerInfoTD[1], true);
TextDrawTextSize(playerInfoTD[1], 49.0000, 49.0000);
TextDrawSetPreviewModel(playerInfoTD[1], 0);
TextDrawSetPreviewRot(playerInfoTD[1], 0.0000, 0.0000, 0.0000, 1.0000);

playerInfoTD[2] = TextDrawCreate(252.0000, 392.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoTD[2], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoTD[2], 0.2099, 1.1000);
TextDrawColour(playerInfoTD[2], -1768515841);
TextDrawSetShadow(playerInfoTD[2], 0);
TextDrawSetOutline(playerInfoTD[2], 0);
TextDrawBackgroundColour(playerInfoTD[2], 255);
TextDrawSetProportional(playerInfoTD[2], true);
TextDrawTextSize(playerInfoTD[2], 64.0000, 3.0000);

playerInfoTD[3] = TextDrawCreate(252.0000, 392.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoTD[3], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoTD[3], 0.2099, 1.1000);
TextDrawColour(playerInfoTD[3], -16776961);
TextDrawSetShadow(playerInfoTD[3], 0);
TextDrawSetOutline(playerInfoTD[3], 0);
TextDrawBackgroundColour(playerInfoTD[3], 255);
TextDrawSetProportional(playerInfoTD[3], true);
TextDrawTextSize(playerInfoTD[3], 55.0000, 3.0000);

playerInfoTD[4] = TextDrawCreate(320.5000, 392.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoTD[4], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoTD[4], 0.2099, 1.1000);
TextDrawColour(playerInfoTD[4], -1768515841);
TextDrawSetShadow(playerInfoTD[4], 0);
TextDrawSetOutline(playerInfoTD[4], 0);
TextDrawBackgroundColour(playerInfoTD[4], 255);
TextDrawSetProportional(playerInfoTD[4], true);
TextDrawTextSize(playerInfoTD[4], 64.0000, 3.0000);

playerInfoTD[5] = TextDrawCreate(321.0000, 392.0000, "LD_SPAC:WHITE");
TextDrawFont(playerInfoTD[5], TEXT_DRAW_FONT:4);
TextDrawLetterSize(playerInfoTD[5], 0.2099, 1.1000);
TextDrawColour(playerInfoTD[5], -1);
TextDrawSetShadow(playerInfoTD[5], 0);
TextDrawSetOutline(playerInfoTD[5], 0);
TextDrawBackgroundColour(playerInfoTD[5], 255);
TextDrawSetProportional(playerInfoTD[5], true);
TextDrawTextSize(playerInfoTD[5], 10.5000, 3.0000);

playerInfoTD[6] = TextDrawCreate(341.0000, 376.0000, "MAX PLAYER SPEED: 35.0");
TextDrawFont(playerInfoTD[6], TEXT_DRAW_FONT:1);
TextDrawLetterSize(playerInfoTD[6], 0.1199, 0.5999);
TextDrawColour(playerInfoTD[6], 1684301055);
TextDrawSetShadow(playerInfoTD[6], 0);
TextDrawSetOutline(playerInfoTD[6], 0);
TextDrawBackgroundColour(playerInfoTD[6], 255);
TextDrawSetProportional(playerInfoTD[6], true);
TextDrawTextSize(playerInfoTD[6], 640.0000, 0.0000);

/*****************
* VEHICLE INFO FRAME
*****************/
vehicleInfoFrameTD[0] = TextDrawCreate(218.0000, 403.5000, "LD_SPAC:WHITE");
TextDrawFont(vehicleInfoFrameTD[0], TEXT_DRAW_FONT:4);
TextDrawLetterSize(vehicleInfoFrameTD[0], 0.5000, 1.0000);
TextDrawColour(vehicleInfoFrameTD[0], 1094795775);
TextDrawSetShadow(vehicleInfoFrameTD[0], 0);
TextDrawSetOutline(vehicleInfoFrameTD[0], 0);
TextDrawBackgroundColour(vehicleInfoFrameTD[0], 255);
TextDrawSetProportional(vehicleInfoFrameTD[0], true);
TextDrawTextSize(vehicleInfoFrameTD[0], 200.0000, 32.0000);

vehicleInfoFrameTD[1] = TextDrawCreate(219.0000, 404.5000, "LD_SPAC:WHITE");
TextDrawFont(vehicleInfoFrameTD[1], TEXT_DRAW_FONT:4);
TextDrawLetterSize(vehicleInfoFrameTD[1], 0.5000, 1.0000);
TextDrawColour(vehicleInfoFrameTD[1], 589505535);
TextDrawSetShadow(vehicleInfoFrameTD[1], 0);
TextDrawSetOutline(vehicleInfoFrameTD[1], 0);
TextDrawBackgroundColour(vehicleInfoFrameTD[1], 255);
TextDrawSetProportional(vehicleInfoFrameTD[1], true);
TextDrawTextSize(vehicleInfoFrameTD[1], 198.0000, 30.0000);

/*****************
* VEHICLE INFO TEXTS
*****************/
vehicleInfoTD[0] = TextDrawCreate(252.0000, 406.0000, "PLAYER VEHICLE INFO:");
TextDrawFont(vehicleInfoTD[0], TEXT_DRAW_FONT:1);
TextDrawLetterSize(vehicleInfoTD[0], 0.1399, 0.7999);
TextDrawColour(vehicleInfoTD[0], -1768515841);
TextDrawSetShadow(vehicleInfoTD[0], 0);
TextDrawSetOutline(vehicleInfoTD[0], 0);
TextDrawBackgroundColour(vehicleInfoTD[0], 255);
TextDrawSetProportional(vehicleInfoTD[0], true);
TextDrawTextSize(vehicleInfoTD[0], 640.0000, 0.0000);

vehicleInfoTD[1] = TextDrawCreate(220.5000, 406.5000, "PLAYER_MODEL");
TextDrawFont(vehicleInfoTD[1], TEXT_DRAW_FONT:5);
TextDrawLetterSize(vehicleInfoTD[1], 0.2099, 1.1000);
TextDrawColour(vehicleInfoTD[1], -1);
TextDrawSetShadow(vehicleInfoTD[1], 0);
TextDrawSetOutline(vehicleInfoTD[1], 0);
TextDrawBackgroundColour(vehicleInfoTD[1], 842150655);
TextDrawSetProportional(vehicleInfoTD[1], true);
TextDrawTextSize(vehicleInfoTD[1], 30.0000, 26.0000);
TextDrawSetPreviewModel(vehicleInfoTD[1], 456);
TextDrawSetPreviewRot(vehicleInfoTD[1], 0.0000, 0.0000, -50.0000, 1.0000);

vehicleInfoTD[2] = TextDrawCreate(320.5000, 429.0000, "LD_SPAC:WHITE");
TextDrawFont(vehicleInfoTD[2], TEXT_DRAW_FONT:4);
TextDrawLetterSize(vehicleInfoTD[2], 0.2099, 1.1000);
TextDrawColour(vehicleInfoTD[2], -1768515841);
TextDrawSetShadow(vehicleInfoTD[2], 0);
TextDrawSetOutline(vehicleInfoTD[2], 0);
TextDrawBackgroundColour(vehicleInfoTD[2], 255);
TextDrawSetProportional(vehicleInfoTD[2], true);
TextDrawTextSize(vehicleInfoTD[2], 94.5000, 3.0000);

vehicleInfoTD[3] = TextDrawCreate(320.5000, 429.0000, "LD_SPAC:WHITE");
TextDrawFont(vehicleInfoTD[3], TEXT_DRAW_FONT:4);
TextDrawLetterSize(vehicleInfoTD[3], 0.2099, 1.1000);
TextDrawColour(vehicleInfoTD[3], -16776961);
TextDrawSetShadow(vehicleInfoTD[3], 0);
TextDrawSetOutline(vehicleInfoTD[3], 0);
TextDrawBackgroundColour(vehicleInfoTD[3], 255);
TextDrawSetProportional(vehicleInfoTD[3], true);
TextDrawTextSize(vehicleInfoTD[3], 94.5000, 3.0000);

animDraw = TextDrawCreate(405.500000, 420.000000, "~y~~k~~PED_SPRINT~ ~g~to stop animation");
TextDrawLetterSize(animDraw, 0.333499, 1.337500);
TextDrawAlignment(animDraw, TEXT_DRAW_ALIGN:1);
TextDrawColour(animDraw, -1);
TextDrawSetShadow(animDraw, 0);
TextDrawSetOutline(animDraw, 1);
TextDrawBackgroundColour(animDraw, 51);
TextDrawFont(animDraw, TEXT_DRAW_FONT:2);
TextDrawSetProportional(animDraw, true);

chooseCar_TD[0] = TextDrawCreate(186.0000, 308.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[0], 0.0000, 11.1434);
TextDrawTextSize(chooseCar_TD[0], 260.9498, 0.0000);
TextDrawAlignment(chooseCar_TD[0], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[0], -1);
TextDrawUseBox(chooseCar_TD[0], true);
TextDrawBoxColour(chooseCar_TD[0], 3567282);
TextDrawBackgroundColour(chooseCar_TD[0], 255);
TextDrawFont(chooseCar_TD[0], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[0], true);
TextDrawSetShadow(chooseCar_TD[0], 0);

chooseCar_TD[1] = TextDrawCreate(202.0000, 308.0000, "COLOR"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[1], 0.4000, 1.6000);
TextDrawTextSize(chooseCar_TD[1], 19.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[1], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[1], -1);
TextDrawBackgroundColour(chooseCar_TD[1], 255);
TextDrawFont(chooseCar_TD[1], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[1], true);
TextDrawSetShadow(chooseCar_TD[1], 1);

chooseCar_TD[2] = TextDrawCreate(191.0000, 330.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[2], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[2], 206.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[2], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[2], -65281);
TextDrawUseBox(chooseCar_TD[2], true);
TextDrawBoxColour(chooseCar_TD[2], -65281);
TextDrawBackgroundColour(chooseCar_TD[2], 255);
TextDrawFont(chooseCar_TD[2], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[2], true);
TextDrawSetShadow(chooseCar_TD[2], 0);
TextDrawSetSelectable(chooseCar_TD[2], true);

chooseCar_TD[3] = TextDrawCreate(215.2998, 330.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[3], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[3], 230.2998, 0.0000);
TextDrawAlignment(chooseCar_TD[3], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[3], -65281);
TextDrawUseBox(chooseCar_TD[3], true);
TextDrawBoxColour(chooseCar_TD[3], -1);
TextDrawBackgroundColour(chooseCar_TD[3], 255);
TextDrawFont(chooseCar_TD[3], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[3], true);
TextDrawSetShadow(chooseCar_TD[3], 0);
TextDrawSetSelectable(chooseCar_TD[3], true);

chooseCar_TD[4] = TextDrawCreate(240.0000, 330.2998, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[4], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[4], 255.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[4], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[4], -65281);
TextDrawUseBox(chooseCar_TD[4], true);
TextDrawBoxColour(chooseCar_TD[4], 255);
TextDrawBackgroundColour(chooseCar_TD[4], 255);
TextDrawFont(chooseCar_TD[4], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[4], true);
TextDrawSetShadow(chooseCar_TD[4], 0);
TextDrawSetSelectable(chooseCar_TD[4], true);

chooseCar_TD[5] = TextDrawCreate(191.0000, 357.9000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[5], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[5], 206.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[5], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[5], -65281);
TextDrawUseBox(chooseCar_TD[5], true);
TextDrawBoxColour(chooseCar_TD[5], 91750399);
TextDrawBackgroundColour(chooseCar_TD[5], 255);
TextDrawFont(chooseCar_TD[5], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[5], true);
TextDrawSetShadow(chooseCar_TD[5], 0);
TextDrawSetSelectable(chooseCar_TD[5], true);

chooseCar_TD[6] = TextDrawCreate(215.4998, 358.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[6], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[6], 230.4998, 0.0000);
TextDrawAlignment(chooseCar_TD[6], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[6], -65281);
TextDrawUseBox(chooseCar_TD[6], true);
TextDrawBoxColour(chooseCar_TD[6], 8405247);
TextDrawBackgroundColour(chooseCar_TD[6], 255);
TextDrawFont(chooseCar_TD[6],TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[6], true);
TextDrawSetShadow(chooseCar_TD[6], 0);
TextDrawSetSelectable(chooseCar_TD[6], true);

chooseCar_TD[7] = TextDrawCreate(240.1000, 358.1000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[7], 0.0000, 1.8945);
TextDrawTextSize(chooseCar_TD[7], 255.1000, 0.0000);
TextDrawAlignment(chooseCar_TD[7], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[7], -65281);
TextDrawUseBox(chooseCar_TD[7], true);
TextDrawBoxColour(chooseCar_TD[7], -16776961);
TextDrawBackgroundColour(chooseCar_TD[7], 255);
TextDrawFont(chooseCar_TD[7], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[7], true);
TextDrawSetShadow(chooseCar_TD[7], 0);
TextDrawSetSelectable(chooseCar_TD[7], true);

chooseCar_TD[8] = TextDrawCreate(193.8999, 386.0000, "select"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[8], 0.4009, 1.6174);
TextDrawTextSize(chooseCar_TD[8], 254.0000, 15.0000);
TextDrawAlignment(chooseCar_TD[8], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[8], -1);
TextDrawBackgroundColour(chooseCar_TD[8], 255);
TextDrawFont(chooseCar_TD[8], TEXT_DRAW_FONT:2);
TextDrawSetProportional(chooseCar_TD[8], true);
TextDrawSetShadow(chooseCar_TD[8], 1);
TextDrawSetSelectable(chooseCar_TD[8], true);

chooseCar_TD[9] = TextDrawCreate(267.0000, 308.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[9], 0.0000, 11.1443);
TextDrawTextSize(chooseCar_TD[9], 388.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[9], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[9], -1);
TextDrawUseBox(chooseCar_TD[9], true);
TextDrawBoxColour(chooseCar_TD[9], 3567282);
TextDrawBackgroundColour(chooseCar_TD[9], 255);
TextDrawFont(chooseCar_TD[9], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[9], true);
TextDrawSetShadow(chooseCar_TD[9], 0);

chooseCar_TD[10] = TextDrawCreate(353.0000, 361.0000, ""); // ˜˜˜˜˜
TextDrawTextSize(chooseCar_TD[10], 35.0000, 64.0000);
TextDrawAlignment(chooseCar_TD[10], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[10], -1056964353);
TextDrawBackgroundColour(chooseCar_TD[10], 0);
TextDrawFont(chooseCar_TD[10], TEXT_DRAW_FONT:5);
TextDrawSetProportional(chooseCar_TD[10], false);
TextDrawSetShadow(chooseCar_TD[10], 0);
TextDrawSetSelectable(chooseCar_TD[10], true);
TextDrawSetPreviewModel(chooseCar_TD[10], 19133);
TextDrawSetPreviewRot(chooseCar_TD[10], 2.0000, 90.0000, 270.0000, 1.0000);

chooseCar_TD[11] = TextDrawCreate(326.0000, 384.0000, "BUY"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[11], 0.4641, 1.9207);
TextDrawTextSize(chooseCar_TD[11], 50.0000, 15.0000);
TextDrawAlignment(chooseCar_TD[11], TEXT_DRAW_ALIGN:2);
TextDrawColour(chooseCar_TD[11], -1);
TextDrawBackgroundColour(chooseCar_TD[11], 148);
TextDrawFont(chooseCar_TD[11], TEXT_DRAW_FONT:2);
TextDrawSetProportional(chooseCar_TD[11], true);
TextDrawSetShadow(chooseCar_TD[11], 1);
TextDrawSetSelectable(chooseCar_TD[11], true);

chooseCar_TD[12] = TextDrawCreate(264.0000, 361.0000, ""); // ˜˜˜˜˜
TextDrawTextSize(chooseCar_TD[12], 35.0000, 64.0000);
TextDrawAlignment(chooseCar_TD[12], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[12], -1056964353);
TextDrawBackgroundColour(chooseCar_TD[12], 0);
TextDrawFont(chooseCar_TD[12], TEXT_DRAW_FONT:5);
TextDrawSetProportional(chooseCar_TD[12], false);
TextDrawSetShadow(chooseCar_TD[12], 0);
TextDrawSetSelectable(chooseCar_TD[12], true);
TextDrawSetPreviewModel(chooseCar_TD[12], 19133);
TextDrawSetPreviewRot(chooseCar_TD[12], 2.0000, -90.0000, 270.0000, 1.0000);

chooseCar_TD[13] = TextDrawCreate(404.0000, 308.0000, "INFO"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[13], 0.4000, 1.6000);
TextDrawAlignment(chooseCar_TD[13], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[13], -1);
TextDrawBackgroundColour(chooseCar_TD[13], 255);
TextDrawFont(chooseCar_TD[13], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[13], true);
TextDrawSetShadow(chooseCar_TD[13], 1);

chooseCar_TD[14] = TextDrawCreate(394.0000, 386.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[14], 0.0000, 2.4706);
TextDrawTextSize(chooseCar_TD[14], 442.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[14], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[14], -1);
TextDrawUseBox(chooseCar_TD[14], true);
TextDrawBoxColour(chooseCar_TD[14], 3567282);
TextDrawBackgroundColour(chooseCar_TD[14], 255);
TextDrawFont(chooseCar_TD[14], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[14], true);
TextDrawSetShadow(chooseCar_TD[14], 0);

chooseCar_TD[15] = TextDrawCreate(419.0000, 389.0000, "EXIT"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[15], 0.4000, 1.6000);
TextDrawTextSize(chooseCar_TD[15], 52.0000, 15.0000);
TextDrawAlignment(chooseCar_TD[15], TEXT_DRAW_ALIGN:2);
TextDrawColour(chooseCar_TD[15], -1);
TextDrawBackgroundColour(chooseCar_TD[15], 255);
TextDrawFont(chooseCar_TD[15], TEXT_DRAW_FONT:2);
TextDrawSetProportional(chooseCar_TD[15], true);
TextDrawSetShadow(chooseCar_TD[15], 1);
TextDrawSetSelectable(chooseCar_TD[15], true);

chooseCar_TD[16] = TextDrawCreate(394.0000, 308.0000, "Box"); // ˜˜˜˜˜
TextDrawLetterSize(chooseCar_TD[16], 0.0000, 7.8637);
TextDrawTextSize(chooseCar_TD[16], 442.0000, 0.0000);
TextDrawAlignment(chooseCar_TD[16], TEXT_DRAW_ALIGN:1);
TextDrawColour(chooseCar_TD[16], -1);
TextDrawUseBox(chooseCar_TD[16], true);
TextDrawBoxColour(chooseCar_TD[16], 3567282);
TextDrawBackgroundColour(chooseCar_TD[16], 255);
TextDrawFont(chooseCar_TD[16], TEXT_DRAW_FONT:1);
TextDrawSetProportional(chooseCar_TD[16], false);
TextDrawSetShadow(chooseCar_TD[16], 0);